In [4]:
import torch.nn as nn
import torch

# target output size of 5x7
m = nn.AdaptiveMaxPool2d((10,10))
input = torch.randn(64, 8, 9)
output = m(input)
output.shape

torch.Size([64, 10, 10])

In [5]:
import torch
import torch.nn as nn

# Create input tensor
input_tensor = torch.randn(512, 1024, 555)

# Define output size
output_size = (512, 512)

# Pass input tensor through AdaptiveAvgPool2d
output_tensor = nn.AdaptiveAvgPool2d(output_size)(input_tensor)

# Print output size
print(output_tensor.shape)

torch.Size([512, 512, 512])


In [5]:
import torch
import torch.nn as nn
import torch.nn.utils.rnn as rnn
import torch.nn.functional as F

# Create a packed sequence
data = torch.randn(5, 3)
#lengths = [3, 2, 3]
packed_sequence = rnn.pack_sequence(data, enforce_sorted=False)

# Unpack the packed sequence
unpacked_sequence, _ = rnn.pad_packed_sequence(packed_sequence)

# Add zeros to the start and end of the sequences
pad_size = (0, 0, 1, 1)
padded_sequence = F.pad(unpacked_sequence, pad_size)

# Print the padded sequence
print(padded_sequence)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.3731,  0.3512, -2.9364, -0.1281,  0.4971],
        [ 0.6286,  0.2063,  1.6442, -1.0246, -1.5172],
        [ 0.4563, -0.5586,  0.8302,  0.8978,  0.1929],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [11]:
unpacked_sequence, data, packed_sequence

(tensor([[-0.3731,  0.3512, -2.9364, -0.1281,  0.4971],
         [ 0.6286,  0.2063,  1.6442, -1.0246, -1.5172],
         [ 0.4563, -0.5586,  0.8302,  0.8978,  0.1929]]),
 tensor([[-0.3731,  0.6286,  0.4563],
         [ 0.3512,  0.2063, -0.5586],
         [-2.9364,  1.6442,  0.8302],
         [-0.1281, -1.0246,  0.8978],
         [ 0.4971, -1.5172,  0.1929]]),
 PackedSequence(data=tensor([-0.3731,  0.3512, -2.9364, -0.1281,  0.4971,  0.6286,  0.2063,  1.6442,
         -1.0246, -1.5172,  0.4563, -0.5586,  0.8302,  0.8978,  0.1929]), batch_sizes=tensor([5, 5, 5]), sorted_indices=tensor([0, 1, 2, 3, 4]), unsorted_indices=tensor([0, 1, 2, 3, 4])))