In [4]:
import torch.nn as nn
import torch

# target output size of 5x7
m = nn.AdaptiveMaxPool2d((10,10))
input = torch.randn(64, 8, 9)
output = m(input)
output.shape

torch.Size([64, 10, 10])

In [5]:
import torch
import torch.nn as nn

# Create input tensor
input_tensor = torch.randn(512, 1024, 555)

# Define output size
output_size = (512, 512)

# Pass input tensor through AdaptiveAvgPool2d
output_tensor = nn.AdaptiveAvgPool2d(output_size)(input_tensor)

# Print output size
print(output_tensor.shape)

torch.Size([512, 512, 512])


In [5]:
import torch
import torch.nn as nn
import torch.nn.utils.rnn as rnn
import torch.nn.functional as F

# Create a packed sequence
data = torch.randn(5, 3)
#lengths = [3, 2, 3]
packed_sequence = rnn.pack_sequence(data, enforce_sorted=False)

# Unpack the packed sequence
unpacked_sequence, _ = rnn.pad_packed_sequence(packed_sequence)

# Add zeros to the start and end of the sequences
pad_size = (0, 0, 1, 1)
padded_sequence = F.pad(unpacked_sequence, pad_size)

# Print the padded sequence
print(padded_sequence)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.3731,  0.3512, -2.9364, -0.1281,  0.4971],
        [ 0.6286,  0.2063,  1.6442, -1.0246, -1.5172],
        [ 0.4563, -0.5586,  0.8302,  0.8978,  0.1929],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [11]:
unpacked_sequence, data, packed_sequence

(tensor([[-0.3731,  0.3512, -2.9364, -0.1281,  0.4971],
         [ 0.6286,  0.2063,  1.6442, -1.0246, -1.5172],
         [ 0.4563, -0.5586,  0.8302,  0.8978,  0.1929]]),
 tensor([[-0.3731,  0.6286,  0.4563],
         [ 0.3512,  0.2063, -0.5586],
         [-2.9364,  1.6442,  0.8302],
         [-0.1281, -1.0246,  0.8978],
         [ 0.4971, -1.5172,  0.1929]]),
 PackedSequence(data=tensor([-0.3731,  0.3512, -2.9364, -0.1281,  0.4971,  0.6286,  0.2063,  1.6442,
         -1.0246, -1.5172,  0.4563, -0.5586,  0.8302,  0.8978,  0.1929]), batch_sizes=tensor([5, 5, 5]), sorted_indices=tensor([0, 1, 2, 3, 4]), unsorted_indices=tensor([0, 1, 2, 3, 4])))

In [14]:
import torch

# Define the fixed size you want your tensor to be
fixed_size = (50, 20)

# Define your input tensor
input_tensor = torch.randn(35, 20)

# Calculate the amount of padding to add to the tensor
padding = (fixed_size[1]-input_tensor.size()[1], fixed_size[1]-input_tensor.size()[1],
            (fixed_size[0]-input_tensor.size()[0])//2, (fixed_size[0]-input_tensor.size()[0])//2)

# Apply the padding
padded_tensor = torch.nn.functional.pad(input_tensor, padding)

# Check the size of the padded tensor
print(padded_tensor.size()) # torch.Size([50, 20])


torch.Size([49, 20])


In [5]:
padding

(0, 10)

In [17]:
import torch

# Define the fixed size you want your tensor to be
fixed_size = (50, 20)

# Define your input tensor
input_tensor = torch.randn(40, 20)

# Calculate the amount of padding to add to the tensor
padding = ( (fixed_size[1]-input_tensor.size()[1])//2, (fixed_size[0]-input_tensor.size()[0])//2)

# Define the padding module
pad = torch.nn.ConstantPad2d(padding, 0)

# Pass your input tensor to the padding module
padded_tensor = pad(input_tensor)

# Check the size of the padded tensor
print(padded_tensor.size()) # torch.Size([50, 20])


torch.Size([40, 25])


In [49]:
import torch
from torch import nn
import math

target_pad = (10,2)
x = torch.ones(5,2)

num = target_pad[0] - x.size()[0]
RU_num = math.ceil(num/2)
RD_num = math.floor(num/2)

padded = nn.ConstantPad1d((RD_num, RU_num), 0)(x.T)
padded.T.shape

torch.Size([10, 2])

In [48]:
num, RU_num, RD_num

(5, 3, 2)

In [50]:
padded.T

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])