In [1]:
%cd ..
%load_ext autoreload
%autoreload 2

/home/clay/userdata/title_generation


In [2]:
from pathlib import Path
from pyabc import pyabc
import shutil
import pandas as pd
import numpy as np
import json
import pickle

from data_utils import prepare_abc

import tiktoken
from openai.embeddings_utils import get_embedding
from sentence_transformers import SentenceTransformer


In [23]:
session_dir = Path('abc_dataset/folk_rnn_abc_key_cleaned_for_title/')
session_abcs = list(session_dir.rglob('*.abc'))
session_abcs.sort(key=lambda x: int(x.stem))

In [24]:
session_tunes, error_list = prepare_abc(session_abcs)

Error in token measure_offset: <Beam "|">
Error in token measure_offset: <Beam "|">
Error in token measure_offset: <Beam "|">
Error in meas_offset_from_repeat_start: <Beam "|:">
Error in meas_offset_from_repeat_start: <Beam "|:">
Error in meas_offset_from_repeat_start: <Beam "|:">


In [25]:
len(session_tunes), len(error_list), len(session_abcs)

(11454, 0, 11454)

In [33]:
unique_title = []
for tune in session_tunes:
    if tune.title not in unique_title:
        unique_title.append(tune.title)
len(unique_title)

5417

In [13]:
# make csv file of unique titles
pd.DataFrame(unique_title).to_csv('unique_titles.csv', index=False)

NameError: name 'unique_title' is not defined

In [56]:
df_origin = pd.read_csv('unique_titles.csv', header=0)
df_origin["combined"] = (
    "Song title: " + df_origin.Title.str.strip())
df_origin.head(10)

Title  \
0                    The Devil In The Kitchen   
1                     10th Bat Crossing Rhine   
2                                  1st August   
3                                2D Or Not 2D   
4                                 The 30 Year   
5                            30th Anniversary   
6                                      5:30am   
7  The 72nd Highlanders' Farewell To Aberdeen   
8                              Tommy Peoples'   
9                79th's Farewell To Gibraltar   

                                            combined  
0               Song title: The Devil In The Kitchen  
1                Song title: 10th Bat Crossing Rhine  
2                             Song title: 1st August  
3                           Song title: 2D Or Not 2D  
4                            Song title: The 30 Year  
5                       Song title: 30th Anniversary  
6                                 Song title: 5:30am  
7  Song title: The 72nd Highlanders' Farewell To ...  
8                         Song title: Tommy Peoples'  
9           Song title: 79th's Farewell To Gibraltar

## opeanai sentence emb model

In [3]:
import os
import openai
openai.organization = "clayryu"
openai.api_key = "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"
#openai.Model.list()

In [4]:
# embedding model parameters
embedding_model = "text-embedding-ada-002"
embedding_encoding = "cl100k_base"  # this the encoding for text-embedding-ada-002
max_tokens = 8000  # the maximum for text-embedding-ada-002 is 8191

In [4]:
df_origin = pd.read_csv('unique_titles_with_embedding_langdetct.csv', header=0)
#df_origin["combined_genre"] = (
#    "Song title: " + df_origin.Title.str.strip() + "; Genre: irish folk music")
df_origin.head(2)

Title Language_azure  \
0  The Devil In The Kitchen        English   
1   10th Bat Crossing Rhine        English   

                               combined  \
0  Song title: The Devil In The Kitchen   
1   Song title: 10th Bat Crossing Rhine   

                                      combined_genre  \
0  Song title: The Devil In The Kitchen; Genre: i...   
1  Song title: 10th Bat Crossing Rhine; Genre: ir...   

                          ST_embedding_withsongtitle  \
0  [0.030707573518157005, 0.01104187685996294, -0...   
1  [-0.022036369889974594, -0.07493089139461517, ...   

                              OA_embedding_titleonly  \
0  [0.006531674414873123, -0.01711384579539299, -...   
1  [0.002080520149320364, -0.020544277504086494, ...   

                          OA_embedding_withsongtitle  \
0  [0.007431528531014919, -0.017284130677580833, ...   
1  [0.0002703349164221436, -0.027832742780447006,...   

                    OA_embedding_withsongtitle_genre  
0  [-0.00202469015493989, -0.010335808619856834, ...  
1  [-0.006309073884040117, -0.026604685932397842,...

In [11]:
# change column order "combined_genre"
df_origin = df_origin[['Title', 'combined', 'combined_genre', 'ST_embedding_withsongtitle', 'OA_embedding_withsongtitle', 'OA_embedding_withsongtitle_genre']]
df_origin.head(2)

Title                              combined  \
0  The Devil In The Kitchen  Song title: The Devil In The Kitchen   
1   10th Bat Crossing Rhine   Song title: 10th Bat Crossing Rhine   

                                      combined_genre  \
0  Song title: The Devil In The Kitchen; Genre: i...   
1  Song title: 10th Bat Crossing Rhine; Genre: ir...   

                          ST_embedding_withsongtitle  \
0  [0.030707573518157005, 0.01104187685996294, -0...   
1  [-0.022036369889974594, -0.07493089139461517, ...   

                          OA_embedding_withsongtitle  \
0  [0.007431528531014919, -0.017284130677580833, ...   
1  [0.0002703349164221436, -0.027832742780447006,...   

                    OA_embedding_withsongtitle_genre  
0  [-0.00202469015493989, -0.010335808619856834, ...  
1  [-0.006309073884040117, -0.026604685932397842,...

In [13]:
df_origin["OA_embeding_titleonly"] = df_origin.Title.apply(lambda x: get_embedding(x, engine=embedding_model))

In [59]:
# By default, the to_csv method in Pandas converts values to strings when saving to a CSV file. 
#df.to_csv("unique_titles_with_embeddings.csv")

In [12]:
df_origin.OA_embedding_withsongtitle_genre[0][19]

'8'

In [14]:
# Encode the lists as strings before saving
df_origin['OA_embeding_titleonly'] = df_origin['OA_embeding_titleonly'].apply(json.dumps)
df_origin.to_csv('unique_titles_with_embedding.csv', index=False)

In [15]:
df_embedding_all = pd.read_csv('unique_titles_with_embedding.csv')
df_embedding_all["ST_embedding_withsongtitle"] = df_embedding_all["ST_embedding_withsongtitle"].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embedding_withsongtitle'] = df_embedding_all['OA_embedding_withsongtitle'].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embedding_withsongtitle_genre'] = df_embedding_all['OA_embedding_withsongtitle_genre'].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embeding_titleonly'] = df_embedding_all['OA_embeding_titleonly'].apply(lambda x: np.array(eval(x)))

In [17]:
df_embedding_all['OA_embeding_titleonly'][0][19]

-0.03369907662272453

### context comparison
시작은 title only - title with song - title with song with genre  
문맥을 제거하면 그 자체로는 애매한 내용의 단어들이다.

In [36]:
cos_sim_all = []
for i in range(len(df_embedding_all)):
  cos_sim = np.dot(df_embedding_all['OA_embeding_titleonly'][i], df_embedding_all['OA_embedding_withsongtitle'][i]) / (np.linalg.norm(df_embedding_all['OA_embeding_titleonly'][i]) * np.linalg.norm(df_embedding_all['OA_embedding_withsongtitle'][i]))
  cos_sim_all.append(cos_sim)

avg_cosim = sum(cos_sim_all)/len(df_embedding_all)
# pick the lowest 10 of the cosine similarity idx
lowest_idx = np.argsort(cos_sim_all)[:300]

# pick the highest 10 of the cosine similarity idx
highest_idx = np.argsort(cos_sim_all)[-20:]
lowest_idx, highest_idx

(array([ 354, 3084, 2428,  317,   39, 1414, 3984,  381, 4901, 2252, 1502,
        2868, 2708, 3412,  844, 2103, 1131, 5022, 1318, 5308, 3381, 1715,
        2474, 2990,  838, 3133, 4795, 1207, 2075, 4593, 3832, 3842, 3760,
        5186, 2433, 2619,  203, 1748, 1695,  277,  944,  472,  167, 2503,
        1086, 2124, 2072,  115, 2643,  307,  213,  347, 4033, 1278, 2897,
        3703, 1489, 5254,  540, 5378, 3609, 1382, 1231,  957, 3291, 1078,
        2634, 4174, 5043, 1334, 3447, 4612, 1458,  601, 4384, 4108, 4628,
        4216, 2810, 1734, 4630, 5030,  355,  822, 1466, 4896, 2979, 5192,
        1782, 3975, 3490, 5028, 4256, 5397, 4958, 1543, 2808, 2329, 5366,
        3253, 1251, 2891, 4041,  612, 1249, 1287,  817, 2004, 1860, 1317,
        3971,  653, 3498, 3249, 1603, 5083, 2114, 4014, 2883, 4690, 3384,
        3868, 4768, 2490, 4251, 3999, 3985,  505, 3441, 2497,  396, 2240,
        3495, 2822, 2231, 5257, 2253, 1549, 2844, 2148,  621, 3140, 2888,
        5391, 1647, 4418, 2991, 2146, 

In [41]:
# check the title of the lowest 100 cosine similarity
# between the title only and the title + song
list_cmps300 = []
for idx in lowest_idx:
  list_cmps300.append(df_embedding_all.Title[idx])
print(list_cmps300[:50])

['Untitled', 'Home', 'For', 'Apple', 'Christmas', 'Coffee', 'Mary', 'Atlantic', 'Spanish', 'February', 'Cookie Shine', 'Hamilton House', 'September', 'Atlantic Drive', 'Border', 'Empty Wallet', "Stephen Campbell's", 'Summer', 'The Chinese', 'Why So', 'The Japanese', 'David Power', "Fraher's", "Henry Cave's", 'Boolavogue', 'The House', 'Skipping Lambs', 'Castle Dangerous', "Elizabeth Donald's", "Sam Cormier's", "MacDonald's", 'Mad', 'Log Drivers', 'Uist', "Forest Rogers'", 'George Booker', 'Always Welcome', 'Delighted', "Joe Cormier's", 'The Independent', 'Bretonia', "Martin Rochford's", "Alex Burke's", 'Friendsville', 'C+', "Lewis Proudlock's", 'Election', 'Absent Friends', "Sean Reid's", "Anthony Murray's"]


In [38]:
import pickle

list_to_save = list_cmps300
# Save list to a file
with open("list300_ttl-ttlsong.pkl", "wb") as f:
    pickle.dump(list_to_save, f)

# Load list from a file
with open("list300_ttl-ttlsong.pkl", "rb") as f:
    loaded_list = pickle.load(f)

print(loaded_list)

['Untitled', 'Home', 'For', 'Apple', 'Christmas', 'Coffee', 'Mary', 'Atlantic', 'Spanish', 'February', 'Cookie Shine', 'Hamilton House', 'September', 'Atlantic Drive', 'Border', 'Empty Wallet', "Stephen Campbell's", 'Summer', 'The Chinese', 'Why So', 'The Japanese', 'David Power', "Fraher's", "Henry Cave's", 'Boolavogue', 'The House', 'Skipping Lambs', 'Castle Dangerous', "Elizabeth Donald's", "Sam Cormier's", "MacDonald's", 'Mad', 'Log Drivers', 'Uist', "Forest Rogers'", 'George Booker', 'Always Welcome', 'Delighted', "Joe Cormier's", 'The Independent', 'Bretonia', "Martin Rochford's", "Alex Burke's", 'Friendsville', 'C+', "Lewis Proudlock's", 'Election', 'Absent Friends', "Sean Reid's", "Anthony Murray's", 'The American', 'Arthur McBride', "Michael Russell's", "Character's", 'Happy Hours', 'Left-handed', 'The Constitution', 'The Western', "Batchelder's", 'Wood Point', 'Laden Sack', 'Dreaming', 'Catalina', 'Bridge End', 'The International', 'By Accident', 'The German', "Mrs Ryan's", '

In [9]:
# Load list from a file
with open("list300_ttl-ttlsong.pkl", "rb") as f:
    loaded_list = pickle.load(f)
print(loaded_list)

['Home', 'For', 'Apple', 'Christmas', 'Coffee', 'Mary', 'Atlantic', 'Spanish', 'February', 'Cookie Shine', 'Hamilton House', 'September', 'Atlantic Drive', 'Border', 'Empty Wallet', "Stephen Campbell's", 'Summer', 'The Chinese', 'Why So', 'The Japanese', 'David Power', "Fraher's", "Henry Cave's", 'Boolavogue', 'The House', 'Skipping Lambs', 'Castle Dangerous', "Elizabeth Donald's", "Sam Cormier's", "MacDonald's", 'Mad', 'Log Drivers', 'Uist', "Forest Rogers'", 'George Booker', 'Always Welcome', 'Delighted', "Joe Cormier's", 'The Independent', 'Bretonia', "Martin Rochford's", "Alex Burke's", 'Friendsville', 'C+', "Lewis Proudlock's", 'Election', 'Absent Friends', "Sean Reid's", "Anthony Murray's", 'The American', 'Arthur McBride', "Michael Russell's", "Character's", 'Happy Hours', 'Left-handed', 'The Constitution', 'The Western', "Batchelder's", 'Wood Point', 'Laden Sack', 'Dreaming', 'Catalina', 'Bridge End', 'The International', 'By Accident', 'The German', "Mrs Ryan's", 'Supernose', 

In [8]:
with open("list300_ttl-ttlsong.pkl", "wb") as f:
    pickle.dump(loaded_list, f)

In [20]:
# check the title of the lowest 10 cosine similarity
# between the title only and song + genre
for idx in lowest_idx:
  print(df_embedding_all.Title[idx])

For
Untitled
Home
Mad
Henry Cave's
Mary
Apple
C+
Christmas
September
February
Atlantic
Border
Why So
The Chinese
Joe Cormier's
Differentiation
Character's
The House
Spanish
MacDonald's
Coffee
Fraher's
Summer
The Japanese
Sam Cormier's
Martin Rochford's
Blacktown
Empty Wallet
Friendsville
Middle Eastern
Atlantic Drive
Hamilton House
The American
Madam Parisot's
David's
The German
Delighted
Newmarket
Always Welcome
The International
Whose?
Elizabeth Donald's
Jewish
The Constitution
Bretonia
Jerry Holland's
Wood Point
Upper Denton
Lost Indian
The Cambo
Dick Harmon's
Catalina
The New York
Forest Rogers'
Wiseman's
Unlimited
Cookie Shine
Better Than Worse
Skipping Lambs
Batchelder's
Mike Saunders'
The King
Alex Burke's
David Power
Cooper's
Dreaming
The Western
Happy Hours
Michael Russell's
First Prize
Skipper's
Kevin Miller's
New Row
Michael Turner's
The Congress
Hello World
Log Drivers
Anthony Murray's
Durang's
The London
The White House
Henry's
Hanter Dro
Welcome Home
Franklin's
Brother's


In [23]:
# check the title of the highest 10 cosine similarity
for idx in highest_idx:
  print(df_embedding_all.Title[idx])

The Rollicking Boys Of Tandragee
A Tune For The Road
Grandpa Tommy's Ceili Band
Dance Of The Welsh Vicar
The Holm Band Tune
Dancin' At The Gate
The Song Of The Strings
The Great Tune The World Was Waiting For
The Skye Boat Song
The Dance By The Old Sally Tree
Louie's First Tune
A Tune For The Clan
Irish Fiddle Song
A Fisherman's Song For Attracting Seals
Green Grow The Rushes - O
A Tune For A Rose
A Tune For Frankie
The Greenland Man's Tune
A Tune For Dave
A Tune For Emily Ball


## sentence-transformer

In [3]:
STmodel = SentenceTransformer('all-mpnet-base-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/363 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [4]:
# Read the CSV file and decode the strings back to lists
df_embedding = pd.read_csv('unique_titles_with_embedding.csv')
df_embedding['embedding'] = df_embedding['embedding'].apply(json.loads)
df_embedding.embedding[0][19]

-0.031927090138196945

In [5]:
df_embedding["ST_embedding_withsongtitle"] = df_embedding.combined.apply(lambda x: STmodel.encode(x))

In [6]:
dict_embedding = df_embedding.set_index('Title')['ST_embedding_withsongtitle'].to_dict()

In [8]:
dict_embedding['10th Bat Crossing Rhine'].shape

(768,)

In [10]:
# Encode the lists as strings before saving
# To save NumPy arrays to a CSV file, you can convert them to lists before saving and convert them back to arrays after reading. 
df_embedding["ST_embedding_withsongtitle"] = df_embedding["ST_embedding_withsongtitle"].apply(lambda x: x.tolist())
df_embedding.to_csv('unique_titles_with_embedding.csv', index=False)

In [12]:
# Read the CSV file and convert the lists back to arrays
# eval(x) is a function in Python that evaluates a string as a Python expression and returns the result.
df_embedding_two = pd.read_csv('unique_titles_with_embedding.csv')
df_embedding_two["ST_embedding_withsongtitle"] = df_embedding_two["ST_embedding_withsongtitle"].apply(lambda x: np.array(eval(x)))

In [23]:
#df_embedding_two['embedding'] = df_embedding_two['embedding'].apply(lambda x: np.array(eval(x)))
np.array(df_embedding_two.embedding)

array([array([ 0.00743153, -0.01728413, -0.00093461, ..., -0.00134405,
              -0.01323175, -0.01352953])                              ,
       array([ 0.00027033, -0.02783274,  0.00608841, ..., -0.02517305,
              -0.00452349, -0.0296596 ])                              ,
       array([-0.01631737, -0.00714964, -0.01444532, ..., -0.02040667,
              -0.01032283, -0.0216016 ])                              ,
       ...,
       array([-0.02288719, -0.01714275,  0.01744032, ..., -0.01810016,
              -0.01688399, -0.01516325])                              ,
       array([-0.01859044, -0.00582336,  0.00831163, ..., -0.01027881,
              -0.02539087, -0.00571913])                              ,
       array([ 0.00983204, -0.0201353 , -0.00261243, ..., -0.00576613,
              -0.023765  , -0.0246183 ])                              ],
      dtype=object)

## 3D plotting

### Prepare

In [25]:
import numpy as np
from scipy.spatial.distance import cosine
#from sklearn.decomposition import TruncatedSVD
import umap
import pandas as pd

df_embedding_all = pd.read_csv('unique_titles_with_embedding.csv')
df_embedding_all["ST_embedding_withsongtitle"] = df_embedding_all["ST_embedding_withsongtitle"].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embedding_withsongtitle'] = df_embedding_all['OA_embedding_withsongtitle'].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embedding_withsongtitle_genre'] = df_embedding_all['OA_embedding_withsongtitle_genre'].apply(lambda x: np.array(eval(x)))
df_embedding_all['OA_embeding_titleonly'] = df_embedding_all['OA_embeding_titleonly'].apply(lambda x: np.array(eval(x)))

# Sentence embeddings from sentence transformer
sentence_transformer_embeddings = np.stack(df_embedding_all['ST_embedding_withsongtitle'], axis=0)
# Sentence embeddings from OpenAI model
openai_embeddings = np.stack(df_embedding_all['OA_embedding_withsongtitle'], axis=0)
# Sentence embeddings from OpenAI model with genre
openai_embeddings_genre = np.stack(df_embedding_all['OA_embedding_withsongtitle_genre'], axis=0)
# Sentence embeddings from OpenAI model with only title
openai_embeddings_titleonly = np.stack(df_embedding_all['OA_embeding_titleonly'], axis=0)

# normalize embeddings
sentence_transformer_embeddings = sentence_transformer_embeddings / np.linalg.norm(sentence_transformer_embeddings, axis=1, keepdims=True)
openai_embeddings = openai_embeddings / np.linalg.norm(openai_embeddings, axis=1, keepdims=True)
openai_embeddings_genre = openai_embeddings_genre / np.linalg.norm(openai_embeddings_genre, axis=1, keepdims=True)
openai_embeddings_titleonly = openai_embeddings_titleonly / np.linalg.norm(openai_embeddings_titleonly, axis=1, keepdims=True)


### 3D comparison

In [54]:
import plotly.express as px

# Perform dimensionality reduction on OpenAI embeddings using UMAP
reducer = umap.UMAP(n_components=3)
openai_embeddings_reduced = reducer.fit_transform(openai_embeddings[:200])

# Combine the reduced embeddings and the song titles into a data frame
df = pd.DataFrame(openai_embeddings_reduced, columns=['x', 'y', 'z'])
df['songtitle'] = df_embedding_all['Title'][:200]
df['model'] = 'OpenAI'

# Visualize the reduced embeddings using Plotly
fig = px.scatter_3d(df, x='x', y='y',z='z', color='model', text='songtitle')
fig.write_html("3d_plot_openai_emb.html")
fig.show()

In [55]:
reducer2 = umap.UMAP(n_components=3)
sentence_transformer_embeddings_reduced = reducer2.fit_transform(sentence_transformer_embeddings[:200])
df2 = pd.DataFrame(sentence_transformer_embeddings_reduced, columns=['x', 'y', 'z'])
df2['songtitle'] = df_embedding_all['Title'][:200]
df2['model'] = 'Sentence Transformer'

# Visualize the reduced embeddings using Plotly
fig = px.scatter_3d(df2, x='x', y='y',z='z', color='model', text='songtitle')
fig.write_html("3d_plot_ST_emb.html")
fig.show()

In [80]:
reducer3 = umap.UMAP(n_components=3)
openai_embeddings_genre_reduced = reducer3.fit_transform(openai_embeddings_genre[:200])
df3 = pd.DataFrame(openai_embeddings_genre_reduced, columns=['x', 'y', 'z'])
df3['songtitle'] = df_embedding_all['Title'][:200]
df3['model'] = 'OpenAI with genre'

# Visualize the reduced embeddings using Plotly
fig = px.scatter_3d(df3, x='x', y='y',z='z', color='model', text='songtitle')
fig.write_html("3d_plot_openai_emb_genre.html")
fig.show()

In [27]:
import plotly.express as px

# Perform dimensionality reduction on OpenAI embeddings using UMAP
reducer = umap.UMAP(n_components=3)
openai_embeddings_titleonly_reduced = reducer.fit_transform(openai_embeddings_titleonly[:300])

# Combine the reduced embeddings and the song titles into a data frame
df = pd.DataFrame(openai_embeddings_titleonly_reduced, columns=['x', 'y', 'z'])
df['songtitle'] = df_embedding_all['Title'][:300]
df['model'] = 'OpenAI'

# Visualize the reduced embeddings using Plotly
fig = px.scatter_3d(df, x='x', y='y',z='z', color='model', text='songtitle')
fig.write_html("3d_plot_openai_emb_ttlonly.html")
fig.show()

In [29]:
list(df_embedding_all['Title'][:300])

['The Devil In The Kitchen',
 '10th Bat Crossing Rhine',
 '1st August',
 '2D Or Not 2D',
 'The 30 Year',
 '30th Anniversary',
 '5:30am',
 "The 72nd Highlanders' Farewell To Aberdeen",
 "Tommy Peoples'",
 "79th's Farewell To Gibraltar",
 '93 Not Out',
 'A Barrel Of Knives',
 'A Birthday',
 'The Britches',
 'A Bottle Of Vodka, Twenty Marlboro Reds And £50 Cashback, Please',
 'A Breton In Paris',
 'Love At The Window',
 'Molly On The Shore',
 'A Country Wedding',
 'A Cup Of Tea',
 'Trip To The Quarry',
 'A Day And An Age',
 'The Newfoundland',
 'A Deanadh Im',
 'A Dram At The Wake',
 'The Fair Wind',
 'A Favourite Duet By Mr Holmes',
 'A Fig For A Kiss',
 'The Bag Of Spuds',
 'A Fish Out Of Water',
 "A Fisherman's Song For Attracting Seals",
 'A French Dance',
 'A Ghost Of His Former Self',
 'A Glint Of Silver',
 "A Good Night's Sleep",
 'A Great Big Sea Hove In Long Beach',
 'A Highland Quickstep',
 'A Jig For Bernie',
 'A Jig For Christmas',
 'Christmas',
 'A Jig For Jack',
 'A Jig For 

## embedding size check

In [14]:
import openai
response = openai.Embedding.create(
    input="canine companions say",
    engine="text-embedding-ada-002")

print(response)

{
  "data": [
    {
      "embedding": [
        -0.009508328512310982,
        -0.013023052364587784,
        0.006804419681429863,
        -0.03177538886666298,
        -0.020131081342697144,
        0.04506276175379753,
        0.005047057755291462,
        -0.01563052088022232,
        -0.032404039055109024,
        -0.010451302863657475,
        0.03237546607851982,
        0.021645555272698402,
        0.005847157444804907,
        -0.012294390238821507,
        -0.011537152342498302,
        -0.005872160661965609,
        0.031175315380096436,
        -0.00023730637622065842,
        0.007550941314548254,
        -0.009672634303569794,
        -0.012030071578919888,
        -0.002743199234828353,
        -0.008136728778481483,
        -0.046491511166095734,
        -0.017659343779087067,
        0.008415334858000278,
        0.017959382385015488,
        -0.019030943512916565,
        -0.01605914533138275,
        -0.0017564690206199884,
        0.01784508116543293,
        0.01

In [54]:
len(response["data"][0]["embedding"])

1536